exclude: (dist|\.svg|prebid.js)
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.0
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-symlinks
      - id: check-yaml
        args:
          - --allow-multiple-documents
