version: "3.7"
services:
  web-sdk:
    image: nginx:1.20
    volumes:
      - ./browser/dist:/etc/nginx/html:ro,delegated
      - ./nginx/templates:/etc/nginx/templates:ro,delegated
      - ./nginx/tls:/etc/nginx/tls:ro,delegated
    ports:
      - "8181:443"

  web-demo:
    image: nginx:1.20
    volumes:
      - ./demos:/etc/nginx/html:ro,delegated
      - ./nginx/templates:/etc/nginx/templates:ro,delegated
      - ./nginx/tls:/etc/nginx/tls:ro,delegated
    ports:
      - "8180:443"
