version: "3.7"
services:
  web-sdk:
    image: nginx:1.20
    volumes:
      - ./browser/dist:/usr/share/nginx/html:ro,delegated
    ports:
      - "8181:80"

  web-demo:
    image: nginx:1.20
    volumes:
      - ./demos:/usr/share/nginx/html:ro,delegated
    ports:
      - "8180:80"
