defaults: &defaults
  machine:
    image: ubuntu-2004:202201-02
  resource_class: medium

setup_env: &setup_env
  command: |
    echo '. ~/.asdf/asdf.sh' >> $BASH_ENV
    rm -rf ~/.npm

version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-asdf-{{ checksum ".tool-versions" }}
            - v1-asdf-
      - run: if [ ! -d ~/.asdf ]; then git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.0; fi
      - run:
          <<: *setup_env
      - run: asdf plugin add mkcert || true
      - run: asdf plugin add nodejs || true
      - run: asdf plugin add semver || true
      - run: asdf install
      - save_cache:
          key: v1-asdf-{{ checksum ".tool-versions" }}
          paths:
            - ~/.asdf
      - persist_to_workspace:
          root: "~"
          paths:
            - .asdf

  build:
    <<: *defaults
    environment:
      SDK_URI: https://cdn.optable.co/web-sdk/latest/sdk.js
      DCN_HOST: sandbox.optable.co
      DCN_INSECURE: "false"
      DCN_INIT: "true"
      UID2_BASE_URL: https://operator-integ.uidapi.com
    steps:
      - checkout
      - attach_workspace:
          at: "~"
      - run:
          <<: *setup_env
      - run: ./scripts/patch-version.sh "${CIRCLE_TAG:-v0.0.0-${CIRCLE_SHA::7}}"
      - run: |
          export SDK_URI="https://cdn.optable.co/web-sdk/${CIRCLE_TAG}/sdk.js"
          export ADS_HOST="ads.optable.co"
          export ADS_REGION="ca"
          export DCN_HOST="sandbox.optable.co"
          export DCN_SITE="web-sdk-demo"
          export DCN_ID="optable"
          export DCN_INSECURE="false"
          export DCN_INIT="true"
          export UID2_BASE_URL="https://operator-integ.uidapi.com"
          make -j --output-sync
      - persist_to_workspace:
          root: "~"
          paths:
            - project/lib/dist
            - project/browser/dist
            - project/demos/

  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: "~"
      - run:
          <<: *setup_env
      - run:
          name: Setup application credentials
          command: echo $GCLOUD_SERVICE_KEY > ~/key.json

      - run:
          name: Activate GCP service account
          command: gcloud auth activate-service-account --key-file=/home/circleci/key.json
      - run:
          name: Setup NPM registry access
          command: |
            echo '@optable:registry=https://registry.npmjs.org/' > ~/.npmrc
            echo "//registry.npmjs.org/:_authToken=$NPMJS_AUTH_TOKEN" >> ~/.npmrc
      - run: ./scripts/patch-version.sh "${CIRCLE_TAG:-v0.0.0-${CIRCLE_SHA::7}}"
      - run: npm publish --access public

      - run: scripts/gs-publish.sh gs://optable-web-sdk ./browser/dist/sdk.js "${CIRCLE_TAG}"
      - run: DOCKER_BUILDKIT=1 docker build -t gcr.io/optable-platform/optable-web-sdk-demos:${CIRCLE_TAG} ./demos
      - gcp-gcr/gcr-auth
      - run: docker push gcr.io/optable-platform/optable-web-sdk-demos:${CIRCLE_TAG}

workflows:
  test:
    jobs:
      - setup:
          filters:
            tags:
              only: /v.*/
      - build:
          requires:
            - setup
          filters:
            tags:
              only: /v.*/
      - publish:
          context:
            - gcp-prod
            - npm-prod
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
