dind: &dind
  plugins:
    - docker#v3.5.0:
        image: "docker:latest"
        mount-buildkite-agent: false
        propagate-environment: true
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /etc/service_key:/etc/service_key

env:
  DOCKER_BUILDKIT: 1
steps:
  - name: prettier
    if: "!build.pull_request.draft"
    commands:
      - "npm install -g prettier@2.0.4"
      - "prettier --check ."
    plugins:
      - docker#v3.5.0:
          image: "node:14.5.0-alpine3.10"
          mount-buildkite-agent: false
  - name: docker-build-sdk
    <<: *dind
    if: "!build.pull_request.draft"
    commands:
      - "apk add make git"
      - "cat /etc/service_key/service-account-key.json | docker login -u _json_key --password-stdin https://gcr.io"
      - "make build-sdk"
  - name: docker-build-demos
    <<: *dind
    if: "!build.pull_request.draft"
    commands:
      - "apk add make git"
      - "cat /etc/service_key/service-account-key.json | docker login -u _json_key --password-stdin https://gcr.io"
      - "make build-demos"
