env:
  DOCKER_BUILDKIT: 1
steps:
  - name: npm-publish
    commands:
      - apk --update add --no-cache bash
      - npm install -g npm@6.14.5
      - ./scripts/patch-version.sh "$BUILDKITE_TAG"
      - npm ci
      - npm run build-lib
      - echo "@optable:registry=https://registry.npmjs.org/" > ~/.npmrc
      - echo "//registry.npmjs.org/:_authToken=$NPMJS_AUTH_TOKEN" >> ~/.npmrc
      - npm publish --access public

    plugins:
      - docker#v3.5.0:
          image: "node:14.5.0-alpine3.10"
          propagate-environment: true
          mount-buildkite-agent: false
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock

  - name: docker-publish
    commands:
      - "apk add make git"
      - "cat /etc/service_key/service-account-key.json | docker login -u _json_key --password-stdin https://gcr.io"
      - "make TAG=$BUILDKITE_TAG BUILD_VERSION=$BUILDKITE_TAG build publish"
    plugins:
      - docker#v3.5.0:
          image: "docker:latest"
          mount-buildkite-agent: false
          propagate-environment: true
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/service_key:/etc/service_key
