name: "Setup mise"
description: "A composite action to setup mise-en-place tool manager"

runs:
  using: "composite"
  steps:
    - name: Setup mise
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151
      with:
        install: true
        cache: true
