type Region = "eu" | "us" | "ca";

const zones: { [k: string]: Region } = {
  // EU
  "Europe/Amsterdam": "eu",
  "Europe/Athens": "eu",
  "Europe/Berlin": "eu",
  "Europe/Brussels": "eu",
  "Europe/Bucharest": "eu",
  "Europe/Budapest": "eu",
  "Europe/Copenhagen": "eu",
  "Europe/Dublin": "eu",
  "Europe/Helsinki": "eu",
  "Europe/Lisbon": "eu",
  "Europe/London": "eu",
  "Europe/Madrid": "eu",
  "Europe/Oslo": "eu",
  "Europe/Paris": "eu",
  "Europe/Prague": "eu",
  "Europe/Rome": "eu",
  "Europe/Sofia": "eu",
  "Europe/Stockholm": "eu",
  "Europe/Vienna": "eu",
  "Europe/Warsaw": "eu",
  "Europe/Zurich": "eu",

  // CA
  "America/St_Johns": "ca",
  "America/Halifax": "ca",
  "America/Glace_Bay": "ca",
  "America/Moncton": "ca",
  "America/Goose_Bay": "ca",
  "America/Blanc-Sablon": "ca",
  "America/Toronto": "ca",
  "America/Nipigon": "ca",
  "America/Thunder_Bay": "ca",
  "America/Iqaluit": "ca",
  "America/Pangnirtung": "ca",
  "America/Atikokan": "ca",
  "America/Winnipeg": "ca",
  "America/Rainy_River": "ca",
  "America/Resolute": "ca",
  "America/Rankin_Inlet": "ca",
  "America/Regina": "ca",
  "America/Swift_Current": "ca",
  "America/Edmonton": "ca",
  "America/Cambridge_Bay": "ca",
  "America/Yellowknife": "ca",
  "America/Inuvik": "ca",
  "America/Creston": "ca",
  "America/Dawson_Creek": "ca",
  "America/Fort_Nelson": "ca",
  "America/Whitehorse": "ca",
  "America/Dawson": "ca",
  "America/Vancouver": "ca",

  // US
  "America/New_York": "us",
  "America/Detroit": "us",
  "America/Kentucky/Louisville": "us",
  "America/Kentucky/Monticello": "us",
  "America/Indiana/Indianapolis": "us",
  "America/Indiana/Vincennes": "us",
  "America/Indiana/Winamac": "us",
  "America/Indiana/Marengo": "us",
  "America/Indiana/Petersburg": "us",
  "America/Indiana/Vevay": "us",
  "America/Chicago": "us",
  "America/Indiana/Tell_City": "us",
  "America/Indiana/Knox": "us",
  "America/Menominee": "us",
  "America/North_Dakota/Center": "us",
  "America/North_Dakota/New_Salem": "us",
  "America/North_Dakota/Beulah": "us",
  "America/Denver": "us",
  "America/Boise": "us",
  "America/Phoenix": "us",
  "America/Los_Angeles": "us",
  "America/Anchorage": "us",
  "America/Juneau": "us",
  "America/Sitka": "us",
  "America/Metlakatla": "us",
  "America/Yakutat": "us",
  "America/Nome": "us",
  "America/Adak": "us",
  "Pacific/Honolulu": "us",
};

function timezoneRegion(tz: string): Region | null {
  return zones[tz] || null;
}
export { timezoneRegion, Region };
