name: CI to build the sdk
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:

jobs:
  tests-prettier:
    uses: ./.github/workflows/reusable-lint-test.yml
